0.7.187

diff --git a/bin/day_activate b/bin/day_activate
--- a/bin/day_activate
+++ b/bin/day_activate
@@ -13,30 +13,6 @@ if [[ -z "$dayp" ]]; then
     return 1
 fi
 
-if ! which yq &>/dev/null; then
-  echo "yq not found. Installing via conda in base environment..."
-  conda install -c conda-forge yq -y || {
-    echo "Failed to install yq."
-    return 3
-  }
-else
-  echo "yq is already installed."
-fi
-CONFIG_FILE=~/.config/daylily/daylily_cli_global.yaml
-git_tag=$(yq -r '.daylily.git_tag' "$CONFIG_FILE")
-
-if [[ ! -f ~/.config/daylily/$git_tag ]]; then
-    echo ""
-    echo "!!!!"
-    echo "!!!!"
-    echo "    Error: day-clone script not found. Please run 'day-build' to set up the environment."
-    echo "     day-clone was released with tagged version 0.7.180 of daylily, and is a breaking change from previous versions."
-    echo "     You will need to update your local daylily repository to >=0.7.180 to proceed."
-    echo "     If you have existing clusters created prior to 0.7.180, you will need to rebuild and/or rerun dy-b BUILD."
-    echo "!!!!"
-    return 3
-fi
-
 # Attempt to deactivate any existing environment
 source bin/day_deactivate &> /dev/null 
 echo "Attempting to deactivate existing environments & re-init with --project $DP ."
@@ -86,6 +62,32 @@ if [[ "$?" == "3" ]]; then
     colr "ERROR: source bin/util/profile_freshness_warn.bash"  "$DY_WT0" "$DY_WB0" "$DY_WS1" 1>&2
     return 4
 fi
+
+if ! which yq &>/dev/null; then
+  echo "yq not found. Installing via conda in base environment..."
+  conda install -c conda-forge yq -y || {
+    echo "Failed to install yq."
+    return 3
+  }
+else
+  echo "yq is already installed."
+fi
+
+CONFIG_FILE=~/.config/daylily/daylily_cli_global.yaml
+git_tag=$(yq -r '.daylily.git_tag' "$CONFIG_FILE")
+
+if [[ ! -f ~/.config/daylily/$git_tag ]]; then
+    echo ""
+    echo "!!!!"
+    echo "!!!!"
+    echo "    Error: day-clone script not found. Please run 'day-build' to set up the environment."
+    echo "     day-clone was released with tagged version 0.7.180 of daylily, and is a breaking change from previous versions."
+    echo "     You will need to update your local daylily repository to >=0.7.180 to proceed."
+    echo "     If you have existing clusters created prior to 0.7.180, you will need to rebuild and/or rerun dy-b BUILD."
+    echo "!!!!"
+    return 3
+fi
+
 
 
 # Verify profile exists
