X

diff --git a/bin/day_activate b/bin/day_activate
--- a/bin/day_activate
+++ b/bin/day_activate
@@ -56,7 +56,7 @@ if [[ -f "$profile_info" ]]; then
 
     # Source the environment script
     source "$env_script"
-    ret_code=$?
+    pe_ret_code=$?
     export DYPS1="$mgps1val"
 else
     echo "ERROR: Profile '$1' not found."
@@ -70,14 +70,14 @@ if ! command -v colr &> /dev/null; then
 fi
 
 # Check for errors during activation
-if [[ "$ret_code" != "0" ]]; then
+if [[ "$pe_ret_code" != "0" ]]; then
     source bin/util/col_error.bash
-    echo "ERROR: Activation failed with return code $ret_code."
+    echo "ERROR: Activation failed with return code $pe_ret_code."
     echo ""
     echo "Have you run 'day-build'? If so, try 'bin/day_deactivate reset; source dayinit; day-activate local;'"
-    return $ret_code
+    return $pe_ret_code
 else
-
+    conda activate DAY
     colr "       _______ GREAT SUCCESS _______       " "$DY_IT0" "$DY_IB0" "$DY_IS1"
     export PS1="$DYPS1$PS1"
 fi
